export default function Head() {
  return (
    <>
      <title>Den of Degens</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="One-Stop Spot for Opportunities in Web 3" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
